# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build C Project 

on: [push, pull_request]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  prerequisites:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Prerequisites
      run: .\install.bat
      shell: cmd
      working-directory: ${{ github.workspace }}

  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
      
    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      # Add additional options to the MSBuild command line here (like platform or verbosity level).
      # See https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference
      run: |
          "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\Tools\VsDevCmd.bat"
          msbuild your_project.sln /p:Configuration=Release /p:Platform=x64 /p:IncludePath="D:\a\NHF_Farm\NHF_Farm\lib\SDL2\include" /p:LibraryPath="D:\a\NHF_Farm\NHF_Farm\lib\SDL2\lib"e
